version: '3'

services:
  inquizitive-app-container:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inquizitive-app-container
    restart: always
    ports:
      - "8000:3000"
    # volumes:
    #   - .:/app
    #   - /app/node_modules

  # nginx:
  #   image: inquizitive-app-image:latest
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./build:/usr/share/nginx/html:ro
  #   depends_on:
  #     - deployment-prod
