version: '3'

services:
  deployment-prod:
    image: inquizitive-app-deployment-prod:latest
    ports:
      - "3000:80"
    volumes:
      - .:/app
      - /app/node_modules

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./build:/usr/share/nginx/html:ro
    depends_on:
      - deployment-prod
